#include "yamlgen.hpp"

#include "heuristics.hpp"

#include <cmath>
#include <cstring>
#include <ctime>
#include <random>
#include <set>
#include <sstream>

namespace drvinspect {
namespace {

// Single-quote a YAML scalar, doubling any embedded single quotes -- the
// simplest quoting rule that's always safe for arbitrary free text (dates,
// descriptions, copyright strings that may contain colons or '#').
std::string yq(const std::string& s) {
    std::string out = "'";
    for (char c : s) {
        if (c == '\'')
            out += "''";
        else
            out.push_back(c);
    }
    out += "'";
    return out;
}

// A YAML list of scalars, one per line, at the given indent (spaces).
std::string yaml_list(const std::vector<std::string>& items, int indent) {
    std::string pad(indent, ' ');
    std::ostringstream out;
    if (items.empty()) {
        out << pad << "[]\n";
        return out.str();
    }
    for (const auto& it : items)
        out << pad << "- " << it << "\n";
    return out.str();
}

std::string today_utc() {
    auto t = std::time(nullptr);
    std::tm tm{};
    gmtime_s(&tm, &t);
    char buf[16];
    std::strftime(buf, sizeof(buf), "%Y-%m-%d", &tm);
    return buf;
}

// PE TimeDateStamp -> "YYYY-MM-DD HH:MM:SS", matching LOLDrivers' format.
std::string format_pe_timestamp(uint32_t unix_time) {
    std::time_t t = static_cast<std::time_t>(unix_time);
    std::tm tm{};
    gmtime_s(&tm, &t);
    char buf[32];
    std::strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", &tm);
    return buf;
}

// A random UUID v4 (RFC 4122), used as the entry Id for a brand-new driver
// family. If this sample belongs to an EXISTING LOLDrivers entry (a known
// driver name, new version/build), use that entry's Id instead -- don't
// mint a duplicate family for the same driver.
std::string random_uuid4() {
    std::random_device rd;
    std::mt19937_64 gen(rd());
    std::uniform_int_distribution<uint64_t> dist;
    uint64_t hi = dist(gen), lo = dist(gen);
    uint8_t bytes[16];
    std::memcpy(bytes, &hi, 8);
    std::memcpy(bytes + 8, &lo, 8);
    bytes[6] = (bytes[6] & 0x0F) | 0x40;  // version 4
    bytes[8] = (bytes[8] & 0x3F) | 0x80;  // variant 1

    static const char* hexd = "0123456789abcdef";
    std::string out;
    auto put_byte = [&](uint8_t b) {
        out.push_back(hexd[b >> 4]);
        out.push_back(hexd[b & 0xF]);
    };
    for (int i = 0; i < 16; ++i) {
        if (i == 4 || i == 6 || i == 8 || i == 10)
            out.push_back('-');
        put_byte(bytes[i]);
    }
    return out;
}

double shannon_entropy(const uint8_t* data, size_t len) {
    if (len == 0)
        return 0.0;
    size_t counts[256] = {0};
    for (size_t i = 0; i < len; ++i)
        counts[data[i]]++;
    double entropy = 0.0;
    for (size_t c : counts) {
        if (c == 0)
            continue;
        double p = static_cast<double>(c) / static_cast<double>(len);
        entropy -= p * std::log2(p);
    }
    return entropy;
}

std::string hex_double(double d) {
    std::ostringstream ss;
    ss << d;
    return ss.str();
}

std::string to_hex_field(uint32_t v) {
    std::ostringstream ss;
    ss << "0x" << std::hex << v;
    return ss.str();
}

} // namespace

std::string generate_yaml(const std::string& filename, const std::vector<uint8_t>& data,
                          const FileHashes& hashes, const FileHashes& authentihash,
                          const PeInfo& pe, const YamlOptions& opts) {
    std::ostringstream y;

    y << "# DRAFT generated by drvinspect --yaml -- review every field before submitting.\n";
    y << "# Fields marked TODO need manual completion (see notes below).\n";
    y << "Id: " << random_uuid4()
      << "  # TODO: if this is a new build of an EXISTING LOLDrivers driver,\n"
      << "         # replace with that entry's Id instead of a fresh one.\n";
    y << "Tags:\n" << yaml_list({filename}, 0);
    y << "Verified: 'FALSE'\n";
    y << "Author: " << (opts.author.empty() ? yq("TODO: your name / handle") : yq(opts.author)) << "\n";
    y << "Created: " << yq(today_utc()) << "\n";
    y << "MitreID: " << opts.mitre_id << "\n";
    y << "Category: " << opts.category << "\n";
    y << "Commands:\n";
    y << "  Command: '' # TODO: e.g. sc.exe create ... type=kernel && sc.exe start ...\n";
    y << "  Description: ''\n";
    y << "  Usecase: '' # TODO: e.g. Elevate privileges\n";
    y << "  Privileges: kernel\n";
    y << "  OperatingSystem: '' # TODO: e.g. Windows 10\n";
    y << "Resources:\n";
    {
        std::vector<std::string> res = opts.resources;
        if (res.empty())
            res.push_back("TODO # add advisory/CVE/writeup links");
        y << yaml_list(res, 0);
    }
    y << "Detection:\n"
      << "- type: yara_signature\n"
      << "  value: https://github.com/magicsword-io/LOLDrivers/blob/main/detections/yara/yara-rules_vuln_drivers_strict_renamed.yar\n"
      << "- type: sigma_hash\n"
      << "  value: https://github.com/magicsword-io/LOLDrivers/blob/main/detections/sigma/driver_load_win_vuln_drivers.yml\n"
      << "- type: sigma_names\n"
      << "  value: https://github.com/magicsword-io/LOLDrivers/blob/main/detections/sigma/driver_load_win_vuln_drivers_names.yml\n";
    y << "Acknowledgement:\n";
    y << "  Person: ''\n";
    y << "  Handle: ''\n";
    y << "KnownVulnerableSamples:\n";
    y << "- Filename: " << filename << "\n";
    y << "  MD5: " << hashes.md5 << "\n";
    y << "  SHA1: " << hashes.sha1 << "\n";
    y << "  SHA256: " << hashes.sha256 << "\n";
    y << "  Authentihash:\n";
    y << "    MD5: " << authentihash.md5 << "\n";
    y << "    SHA1: " << authentihash.sha1 << "\n";
    y << "    SHA256: " << authentihash.sha256 << "\n";
    y << "  Description: " << yq(opts.description.empty() ? "TODO" : opts.description) << "\n";
    y << "  Company: " << yq(opts.company.empty() ? "TODO" : opts.company) << "\n";
    y << "  InternalName: " << yq(opts.internal_name.empty() ? filename : opts.internal_name) << "\n";
    y << "  OriginalFilename: " << yq(opts.original_filename.empty() ? filename : opts.original_filename) << "\n";
    y << "  FileVersion: " << yq(opts.file_version.empty() ? "TODO" : opts.file_version) << "\n";
    y << "  Product: " << yq(opts.product.empty() ? "TODO" : opts.product) << "\n";
    y << "  ProductVersion: " << yq(opts.product_version.empty() ? "TODO" : opts.product_version) << "\n";
    y << "  Copyright: " << yq(opts.copyright.empty() ? "TODO" : opts.copyright) << "\n";
    y << "  MachineType: " << (pe.machine == 0x8664 ? "AMD64" : pe.machine == 0x014c ? "I386" : "UNKNOWN") << "\n";

    // Imports: unique DLL names, in first-seen order (matches dataset style).
    {
        std::vector<std::string> dlls;
        std::set<std::string> seen;
        for (const auto& sym : pe.imports)
            if (seen.insert(sym.dll).second)
                dlls.push_back(sym.dll);
        y << "  Imports:\n" << yaml_list(dlls, 2);
    }
    y << "  ExportedFunctions: ''\n";
    {
        std::vector<std::string> funcs;
        std::set<std::string> seen;
        for (const auto& sym : pe.imports) {
            if (sym.by_ordinal || sym.name.empty())
                continue;
            if (seen.insert(sym.name).second)
                funcs.push_back(sym.name);
        }
        y << "  ImportedFunctions:\n" << yaml_list(funcs, 2);
    }
    y << "  Signatures:\n";
    y << "  - CertificatesInfo: ''\n";
    y << "    SignerInfo: ''\n";
    y << "    Certificates: [] "
      << "# TODO: full chain -- run `signtool verify /v /pa <file>` or a cert-dump\n"
      << "                     # tool and transcribe Subject/ValidFrom/ValidTo/SerialNumber/etc.\n";
    if (!opts.publisher.empty())
        y << "    # Observed signer (Get-AuthenticodeSignature): " << opts.publisher << "\n";
    y << "  RichPEHeaderHash:\n";
    y << "    MD5: '' # TODO: not yet computed by drvinspect\n";
    y << "    SHA1: ''\n";
    y << "    SHA256: ''\n";

    // Per-section entropy + virtual size, computed from the actual file bytes.
    y << "  Sections:\n";
    for (const auto& s : pe.sections) {
        double ent = 0.0;
        if (s.raw_pointer + s.raw_size <= data.size() && s.raw_size > 0)
            ent = shannon_entropy(data.data() + s.raw_pointer, s.raw_size);
        y << "    " << s.name << ":\n";
        y << "      Entropy: " << hex_double(ent) << "\n";
        y << "      Virtual Size: " << yq(to_hex_field(s.virtual_size)) << "\n";
    }

    y << "  MagicHeader: 50 45 0 0\n";
    y << "  CreationTimestamp: " << yq(format_pe_timestamp(pe.timestamp)) << "\n";
    y << "  Imphash: " << compute_imphash(pe) << "\n";
    y << "  LoadsDespiteHVCI: '' # TODO: test with HVCI enabled, or leave blank if unknown\n";

    return y.str();
}

} // namespace drvinspect
